# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-toml
    -   id: check-added-large-files
    -   id: mixed-line-ending
    -   id: requirements-txt-fixer

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        language_version: python3.8
        args: [--line-length=80]

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        language_version: python3.8

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        language_version: python3.8
        args: ["--ignore=E501"]
        additional_dependencies:
        -   flake8-bugbear
        -   flake8-comprehensions
        -   flake8-simplify
